import type { Metadata } from "next";
import { Red_Hat_Display, Paytone_One } from "next/font/google"; // Import the fonts
import "@/resources/styles/globals.css"; // Import global styles
import Header from "@/components/shared/header/Header";
import Footer from "@/components/shared/footer/Footer";

// Define the fonts with custom CSS variable names
const redHatDisplay = Red_Hat_Display({
  variable: "--font-red-hat-display",
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"], // Include weights defined in typography.css
});

const paytoneOne = Paytone_One({
  variable: "--font-paytone-one",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${paytoneOne.variable} ${redHatDisplay.variable} `}>
        <Header />
        {/*Spacer to prevent header from causing a slight initial scroll*/}
        <div style={{ height: "20px" }}></div>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
